CREATE SCHEMA IF NOT EXISTS TRADEHUB;

DROP TABLE IF EXISTS TRADEHUB.ALADDIN_RAW_TRADES;

CREATE TABLE TRADEHUB.ALADDIN_RAW_TRADES(
    ACCURED_INT varchar(255) null,
    ACCURED_INT_DAYS varchar(255) null
);