//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.02.22 at 03:53:01 PM IST
//


package com.deloitte.sample.integration.demo.publisher.transformation.securitycanon;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.deloitte.sample.integration.demo.publisher.transformation.securitycanon package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.deloitte.sample.integration.demo.publisher.transformation.securitycanon
   *
   */
  public ObjectFactory() {
  }

  /**
   * Create an instance of {@link ASSETS }
   *
   */
  public ASSETS createASSETS() {
    return new ASSETS();
  }

  /**
   * Create an instance of {@link ASSETS.ASSET }
   *
   */
  public ASSETS.ASSET createASSETSASSET() {
    return new ASSETS.ASSET();
  }

  /**
   * Create an instance of {@link ASSETS.ASSET.CREDITENHANCEMENTS }
   *
   */
  public ASSETS.ASSET.CREDITENHANCEMENTS createASSETSASSETCREDITENHANCEMENTS() {
    return new ASSETS.ASSET.CREDITENHANCEMENTS();
  }

  /**
   * Create an instance of {@link ASSETS.ASSET.PUTCALLDETAILS }
   *
   */
  public ASSETS.ASSET.PUTCALLDETAILS createASSETSASSETPUTCALLDETAILS() {
    return new ASSETS.ASSET.PUTCALLDETAILS();
  }

  /**
   * Create an instance of {@link ASSETS.ASSET.FLOATERDETAILS }
   *
   */
  public ASSETS.ASSET.FLOATERDETAILS createASSETSASSETFLOATERDETAILS() {
    return new ASSETS.ASSET.FLOATERDETAILS();
  }

  /**
   * Create an instance of {@link ASSETS.ASSET.CONVERTIBLEDETAILS }
   *
   */
  public ASSETS.ASSET.CONVERTIBLEDETAILS createASSETSASSETCONVERTIBLEDETAILS() {
    return new ASSETS.ASSET.CONVERTIBLEDETAILS();
  }

  /**
   * Create an instance of {@link ASSETS.ASSET.SECURITYRATINGS }
   *
   */
  public ASSETS.ASSET.SECURITYRATINGS createASSETSASSETSECURITYRATINGS() {
    return new ASSETS.ASSET.SECURITYRATINGS();
  }

  /**
   * Create an instance of {@link ASSETS.ASSET.SECTORCLASSIFICATIONS }
   *
   */
  public ASSETS.ASSET.SECTORCLASSIFICATIONS createASSETSASSETSECTORCLASSIFICATIONS() {
    return new ASSETS.ASSET.SECTORCLASSIFICATIONS();
  }

  /**
   * Create an instance of {@link ASSETS.ASSET.SECURITYIDENTIFIERS }
   *
   */
  public ASSETS.ASSET.SECURITYIDENTIFIERS createASSETSASSETSECURITYIDENTIFIERS() {
    return new ASSETS.ASSET.SECURITYIDENTIFIERS();
  }

  /**
   * Create an instance of {@link ASSETS.ASSET.ASSETCLASSIFICATION }
   *
   */
  public ASSETS.ASSET.ASSETCLASSIFICATION createASSETSASSETASSETCLASSIFICATION() {
    return new ASSETS.ASSET.ASSETCLASSIFICATION();
  }

  /**
   * Create an instance of {@link ASSETS.ASSET.COUNTRYCURRENCY }
   *
   */
  public ASSETS.ASSET.COUNTRYCURRENCY createASSETSASSETCOUNTRYCURRENCY() {
    return new ASSETS.ASSET.COUNTRYCURRENCY();
  }

  /**
   * Create an instance of {@link ASSETS.ASSET.SECURITYFLAGS }
   *
   */
  public ASSETS.ASSET.SECURITYFLAGS createASSETSASSETSECURITYFLAGS() {
    return new ASSETS.ASSET.SECURITYFLAGS();
  }

  /**
   * Create an instance of {@link ASSETS.ASSET.ISSUEDETAILS }
   *
   */
  public ASSETS.ASSET.ISSUEDETAILS createASSETSASSETISSUEDETAILS() {
    return new ASSETS.ASSET.ISSUEDETAILS();
  }

  /**
   * Create an instance of {@link ASSETS.ASSET.CDSWAPDETAILS }
   *
   */
  public ASSETS.ASSET.CDSWAPDETAILS createASSETSASSETCDSWAPDETAILS() {
    return new ASSETS.ASSET.CDSWAPDETAILS();
  }

  /**
   * Create an instance of {@link ASSETS.ASSET.SECURITYPERIODICDETAILS }
   *
   */
  public ASSETS.ASSET.SECURITYPERIODICDETAILS createASSETSASSETSECURITYPERIODICDETAILS() {
    return new ASSETS.ASSET.SECURITYPERIODICDETAILS();
  }

  /**
   * Create an instance of {@link ASSETS.ASSET.TRADINGDETAILS }
   *
   */
  public ASSETS.ASSET.TRADINGDETAILS createASSETSASSETTRADINGDETAILS() {
    return new ASSETS.ASSET.TRADINGDETAILS();
  }

  /**
   * Create an instance of {@link ASSETS.ASSET.CREDITENHANCEMENTS.CREDITENHANCEMENT }
   *
   */
  public ASSETS.ASSET.CREDITENHANCEMENTS.CREDITENHANCEMENT createASSETSASSETCREDITENHANCEMENTSCREDITENHANCEMENT() {
    return new ASSETS.ASSET.CREDITENHANCEMENTS.CREDITENHANCEMENT();
  }

  /**
   * Create an instance of {@link ASSETS.ASSET.PUTCALLDETAILS.PUTCALLDETAIL }
   *
   */
  public ASSETS.ASSET.PUTCALLDETAILS.PUTCALLDETAIL createASSETSASSETPUTCALLDETAILSPUTCALLDETAIL() {
    return new ASSETS.ASSET.PUTCALLDETAILS.PUTCALLDETAIL();
  }

  /**
   * Create an instance of {@link ASSETS.ASSET.FLOATERDETAILS.FLOATERDETAIL }
   *
   */
  public ASSETS.ASSET.FLOATERDETAILS.FLOATERDETAIL createASSETSASSETFLOATERDETAILSFLOATERDETAIL() {
    return new ASSETS.ASSET.FLOATERDETAILS.FLOATERDETAIL();
  }

  /**
   * Create an instance of {@link ASSETS.ASSET.CONVERTIBLEDETAILS.CONVERTIBLEDETAIL }
   *
   */
  public ASSETS.ASSET.CONVERTIBLEDETAILS.CONVERTIBLEDETAIL createASSETSASSETCONVERTIBLEDETAILSCONVERTIBLEDETAIL() {
    return new ASSETS.ASSET.CONVERTIBLEDETAILS.CONVERTIBLEDETAIL();
  }

  /**
   * Create an instance of {@link ASSETS.ASSET.SECURITYRATINGS.SECURITYRATING }
   *
   */
  public ASSETS.ASSET.SECURITYRATINGS.SECURITYRATING createASSETSASSETSECURITYRATINGSSECURITYRATING() {
    return new ASSETS.ASSET.SECURITYRATINGS.SECURITYRATING();
  }

  /**
   * Create an instance of {@link ASSETS.ASSET.SECTORCLASSIFICATIONS.SECTORCLASSIFICATION }
   *
   */
  public ASSETS.ASSET.SECTORCLASSIFICATIONS.SECTORCLASSIFICATION createASSETSASSETSECTORCLASSIFICATIONSSECTORCLASSIFICATION() {
    return new ASSETS.ASSET.SECTORCLASSIFICATIONS.SECTORCLASSIFICATION();
  }

}
