//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.02.22 at 03:53:01 PM IST
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.deloitte.com/canon/security/v1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.deloitte.sample.integration.demo.publisher.transformation.securitycanon;
